### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [foo123/area-select.js#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by foo123** [comment]
Hello, thank you for the comment. The actual license is unlicense (i.e public domain) 
Note that since no license is used one can use as one wishes (this can be made even more explicit).

No other license covers what is intended here.

Acknowledgement of the author is welcomed but not required.

**Comment by karan** [comment]
Hey @foo123. That is awesome. I love public domain. However, unfortunately, on github, any code without an explicit license is considered copyrighted. See this: https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by foo123** [comment]
in that case i will consioder adding a dummy unlicense file (e.g wtfpl or sth). Hope this fixes any issue with github. Although in many cases i have explicitly said so as well

**Comment by foo123** [comment]
The relevant article on licenses on the referenced github post does not exclude users from viewing, using or forking the (public) repository (and probably other actions as well). It seems the article just **recommends** one to choose an open source license (i suspect of the MIT/BSD etc. flavor). i dont see an issue with unlicense and in any case if someone mentions license issues, the _unlicense_ intention is explicitly mentioned. i would rather not pollute the repositories with dummy license files so if any issue arises i may add an explicit unlicense link or sth. Thanks again for the interest. 

Btw i really feel kind of awkward with people writing a few lines of code and using MIT licenses or similar. In many cases it seems it has become some kind of "fashion"

**Comment by karan** [comment]
True. I think that's fair. Thanks again
